qms/qms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sys_management.urls')),
    path('', include('accounts.urls'))
]

qms/sys_management/urls.py
from django.urls import path

from .views import (EmployeesView, CreateNewEmployeeView, EditEmployeeView, DeleteEmployeeView)

urlpatterns = [
    path('', EmployeesView.as_view(), name='employees'),
    path('employee/create-employee', CreateNewEmployeeView.as_view(), name='create_employee'),
    path('employee/edit-employee/<str:slug>/', EditEmployeeView.as_view(), name='edit_employee'),
    path('employee/delete-employee/<str:slug>/', DeleteEmployeeView.as_view(), name='delete_employee'),
]

qms/sys_management/models.py
from django.db import models
from .utils import unique_slug_generator
from django.db.models.signals import pre_save
from django.shortcuts import reverse


class Employee(models.Model):
    DEPARTMENT_CHOICES = [
        ("D1", "First department"),
        ("D2", "Second department"),
        ("D3", "Third department"),
        ("D4", "Fourth department"),
    ]

    POSITION_CHOICES = [
        ("IN", "Intern"),
        ("JR", "Junior Software Developer"),
        ("MD", "Software Developer"),
        ("SR", "Senior Developer"),
        ("PM", "Project Manager"),
        ("QA", "QA Engineer"),
        ("BA", "Business Analyst"),
    ]

    name = models.CharField(max_length=30)
    position = models.CharField(max_length=2, choices=POSITION_CHOICES)
    department = models.CharField(max_length=2, choices=DEPARTMENT_CHOICES)
    status = models.BooleanField(default=True)
    slug = models.SlugField(unique=True, blank=True)

    def __str__(self):
        return self.name

    def get_edit_url(self):
        return reverse('edit_employee', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('delete_employee', kwargs={'slug': self.slug})


def pre_save_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance, instance.name, instance.slug)


pre_save.connect(pre_save_slug, sender=Employee)

qms/sys_management/forms.py
from django import forms

from .models import Employee


class CreateNewEmployeeForm(forms.ModelForm):
    name = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your name'
            }
        )
    )
    blank_choice = [('', 'Enter value'), ]
    position = forms.ChoiceField(
        choices=blank_choice + Employee.POSITION_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'form-control',
            }
        )
    )
    department = forms.ChoiceField(
        choices=blank_choice + Employee.DEPARTMENT_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'form-control',
            }
        )
    )

    class Meta:
        model = Employee
        fields = [
            'name',
            'position',
            'department'
        ]


class EditEmployeeForm(forms.ModelForm):
    name = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    position = forms.ChoiceField(
        choices=Employee.POSITION_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'form-control',
            }
        )
    )
    department = forms.ChoiceField(
        choices=Employee.DEPARTMENT_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'form-control',
            }
        )
    )

    status = forms.BooleanField(
        initial=True,
        required=False,
        label='Active/Inactive'
    )

    class Meta:
        model = Employee
        fields = [
            'name',
            'position',
            'department',
            'status'
        ]

qms/sys_management/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.core.paginator import Paginator
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.http import JsonResponse

from .models import Employee
from .forms import (CreateNewEmployeeForm, EditEmployeeForm)


class EmployeesView(View):
    template_name = 'sys_management/employees.html'

    def get(self, request, *args, **kwargs):
        employees = Employee.objects.all().order_by('-pk')
        paginator = Paginator(employees, 10)
        page_number = request.GET.get('page', 1)
        employees = paginator.get_page(page_number)
        context = {
            'page_objects': employees,
            'is_authenticated': request.user.is_authenticated
        }
        return render(request, self.template_name, context)


@method_decorator(login_required, name='dispatch')
class CreateNewEmployeeView(View):
    template_name = 'sys_management/create_employee.html'

    def get(self, request, *args, **kwargs):
        form = CreateNewEmployeeForm()
        context = {
            'form': form
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = CreateNewEmployeeForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('employees')
        context = {'form': form}
        return render(request, self.template_name, context)


@method_decorator(login_required, name='dispatch')
class EditEmployeeView(View):
    template_name = 'sys_management/edit_employee.html'

    def get(self, request, *args, **kwargs):
        employee = get_object_or_404(Employee, slug=kwargs.get('slug'))
        bound_form = EditEmployeeForm(instance=employee)
        context = {
            'form': bound_form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        employee = get_object_or_404(Employee, slug=kwargs.get('slug'))
        form = EditEmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            form.save()
            return redirect('employees')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)


class DeleteEmployeeView(View):
    def get(self, request, *args, **kwargs):
        employee = get_object_or_404(Employee, slug=kwargs.get('slug'))
        data = dict()
        context = {
            'employee': employee
        }
        data['html_form'] = render_to_string(template_name='sys_management/partial_employee_delete.html',
                                             context=context, request=request)
        return JsonResponse(data)

    def post(self, request, *args, **kwargs):
        employee = get_object_or_404(Employee, slug=kwargs.get('slug'))
        data = dict()
        employee.delete()
        data['form_is_valid'] = True
        employees = Employee.objects.all().order_by('-pk')
        paginator = Paginator(employees, 10)
        page_number = request.GET.get('page', 1)
        employees = paginator.get_page(page_number)
        data['html_employee_list'] = render_to_string('sys_management/list_employees.html', {
            'page_objects': employees,
            'user': request.user
        })
        return JsonResponse(data)

qms/sys_management/templates/sys_management/base_qms.html
{% extends 'base.html'%}

{% block base%}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'employees' %}">Management system</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'employees' %}">Employees<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        {% if user.is_authenticated %}
        <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle user-link" href="#" id="navbarDropdown" role="button"
               data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
            </div>
        </div>
        {% else %}
            <form class="form-inline ml-auto">
                <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
                <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
            </form>
        {% endif %}

    </div>
</nav>

{% block body %}

{% endblock %}

{% endblock %}

qms/sys_management/templates/sys_management/create_employee.html
{% extends 'sys_management/base_qms.html' %}

{% block script %}
<style type="text/css">
    #id_status {
    width: 0;
    height: 0;
    display: inline;
    }
</style>
{% endblock %}

{% block title %}
Create employee
{% endblock %}

{% block body %}
<div class="container mt-5">
   <form method="post" novalidate>
        {% csrf_token %}
        {% include 'form.html' %}
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'employees' %}" class="btn btn-primary">Cancel</a>
    </form>
</div>

{% endblock %}

qms/sys_management/templates/sys_management/edit_employee.html
{% extends 'sys_management/base_qms.html' %}

{% block title %}
Edit employee
{% endblock %}

{% block body %}
<div class="container mt-5">
    <form method="post" novalidate>
        {% csrf_token %}
        {% include 'form.html' %}
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'employees' %}" class="btn btn-primary ">Cancel</a>
    </form>
</div>

{% endblock %}

qms/sys_management/templates/sys_management/employees.html
{% extends 'sys_management/base_qms.html' %}

{% block title %}
List of employees
{% endblock %}

{% load static %}
{% block script %}
<script src="https://kit.fontawesome.com/409c563378.js" crossorigin="anonymous"></script>
<script src="{% static 'js/delete.js' %}"></script>
{% endblock %}

{% block body %}
{% if page_objects %}
<div class="container mt-5">
    <table class="table mt-5" id="employee-table">
        <thead class="thead-inverse">
        <tr>
            <th>Name</th>
            <th>Position</th>
            <th>Department</th>
            {% if user.is_authenticated %}
            <th></th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% include 'sys_management/list_employees.html' %}
        </tbody>
    </table>
    <div class="modal fade" id="modal-employee">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>
    <div class="footer">
        {% include 'pagination.html' %}
        {% if user.is_authenticated %}
        <a href="{% url 'create_employee' %}" class="btn btn-primary float-right" role="button">Create new employee</a>
        {% endif %}
    </div>
</div>
{% else %}
<div class="jumbotron">
    <div class="container">
        <h1>Welcome to quality management system</h1>
        <p>In this site you can create, delete and manage your employee. If you are not registered, sign up and get
            started with our system</p>
        <p><a href="{% url 'create_employee' %}" class="btn btn-primary btn-lg">Create new employee</a></p>
    </div>
</div>
{% endif %}
{% endblock %}

qms/sys_management/templates/sys_management/list_employees.html
{% for employee in page_objects %}
<tr {% if not employee.status %} class="table-active" {% endif %}>
    <td>
        <a href="{{ employee.get_edit_url }}">{{ employee.name }}</a>
    </td>
    <td>
        {{ employee.get_position_display }}
    </td>
    <td>
        {{ employee.get_department_display }}
    </td>
    {% if user.is_authenticated %}
    <td>
        <button type="button"
                class="btn btn-danger js-delete-employee"
                data-url="{{ employee.get_delete_url }}">
                <i class="fas fa-trash"></i> Delete
        </button>
    </td>
    {% endif %}
</tr>
{% empty %}
    <tr>
        <td colspan="4" class="text-center bg-warning">No employees</td>
    </tr>
{% endfor %}

qms/sys_management/templates/sys_management/partial_employee_delete.html
<form method="post" action="{{ employee.get_delete_url }}" class="js-employee-delete-form">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Confirm delete</h4>
    </div>
    <div class="modal-body">
        <p class="lead">Are you sure you want to delete the employee <strong>{{ employee.name }}</strong>?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-danger">Delete employee</button>
    </div>
</form>